package nl.vu.psy.ams.suite.data;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import nl.vu.psy.ams.suite.data.structures.AmsLabel;

/*
 * Using the average motiliy signals generated by AverageMotilityFileGenerator,
 * this class calculates a 'total motility' signal, which is simply the sum of
 * each direction. Note that EE2 is not used atm: this was a signal consisting of
 * motility + HRA + log(rmmsd) + ... , but not used anymore. 
 */

public class TotalMotilityGenerator {

	private static double[]	dataEE1			= null;
	private static boolean	isEE1Calculated	= false;
	private static boolean	isEE2Calculated	= false;
	private static double[]	dataEE2;

	public static void clear() {
		isEE1Calculated = false;
		isEE2Calculated = false;
	}

	public static double[] getEE2Data() {
		if (isEE2Calculated)
			return dataEE2;
		isEE2Calculated = true;
		CurrentOpenData cod = CurrentOpenData.getInstance();
		File xFile = new File(cod.getFilePath(), "AVX.dbin");
		File yFile = new File(cod.getFilePath(), "AVY.dbin");
		File zFile = new File(cod.getFilePath(), "AVZ.dbin");

		// AverageMotilityFilesGenerator.generateAvMotFiles();

		if (xFile.exists() == false || yFile.exists() == false || zFile.exists() == false) {
			dataEE2 = null;
			return dataEE2;
		}

		int nVals = (int) Math.round((cod.getEndTimeInUS() - cod.getStartTimeInUS()) / 60000000.);

		dataEE2 = new double[nVals];

		DataInputStream inX = null, inY = null, inZ = null;

		double leftTime = cod.getStartTimeInUS();
		double curTime = leftTime + 500000.;
		double rightTime = leftTime + 60000000.;
		double lastTime = cod.getEndTimeInUS();
		double avX = 0;
		double avY = 0;
		double avZ = 0;
		int nInAv = 0;
		int q = 0;

		try {
			inX = new DataInputStream(new BufferedInputStream(new FileInputStream(xFile)));
			inY = new DataInputStream(new BufferedInputStream(new FileInputStream(yFile)));
			inZ = new DataInputStream(new BufferedInputStream(new FileInputStream(zFile)));
			while (rightTime < lastTime) {
				while (curTime < rightTime) {
					avX += inX.readDouble();
					avY += inY.readDouble();
					avZ += inZ.readDouble();
					nInAv++;
					curTime += 1000000.;
				}
				AmsLabel lab = new AmsLabel(leftTime, rightTime, false, 0.0," ");
				double hr = lab.getAverage(true);
				if (hr < 0)
					hr = 0;
				double rmssd = lab.getRMSSD();
				if (rmssd < 0)
					rmssd = 1;
				Double rr = lab.getRespirationRate();
				if (rr == null)
					rr = 0.;

				if (nInAv > 0) {
					avX /= nInAv;
					avY /= nInAv;
					avZ /= nInAv;
				} else {
					avX = 0;
					avY = 0;
					avZ = 0;
				}

				dataEE2[q] = avX + avY + avZ + hr / 200 + Math.log(rmssd) / 10 + rr / 30;
				q++;
				nInAv = 0;
				avX = 0;
				avY = 0;
				avZ = 0;
				leftTime = rightTime;
				rightTime = leftTime + 60000000.;
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (inX != null) {
				try {
					inX.close();
				} catch (IOException e) {
				}
			}
			if (inY != null) {
				try {
					inY.close();
				} catch (IOException e) {
				}
			}
			if (inZ != null) {
				try {
					inZ.close();
				} catch (IOException e) {
				}
			}
		}

		return dataEE2;
	}

	public static double[] getTotalMotility() {
		if (isEE1Calculated)
			return dataEE1;
		isEE1Calculated = true;
		CurrentOpenData cod = CurrentOpenData.getInstance();
		File xFile = new File(cod.getFilePath(), "AVX.dbin");
		File yFile = new File(cod.getFilePath(), "AVY.dbin");
		File zFile = new File(cod.getFilePath(), "AVZ.dbin");

		// AverageMotilityFilesGenerator.generateAvMotFiles();

		if (xFile.exists() == false || yFile.exists() == false || zFile.exists() == false) {
			dataEE1 = null;
			return dataEE1;
		}

		int nVals = (int) (xFile.length() / 8);

		dataEE1 = new double[nVals];

		DataInputStream inX = null, inY = null, inZ = null;

		try {
			inX = new DataInputStream(new BufferedInputStream(new FileInputStream(xFile)));
			inY = new DataInputStream(new BufferedInputStream(new FileInputStream(yFile)));
			inZ = new DataInputStream(new BufferedInputStream(new FileInputStream(zFile)));
			for (int i = 0; i < nVals; i++) {
				dataEE1[i] = inX.readDouble() + inY.readDouble() + inZ.readDouble();
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (inX != null) {
				try {
					inX.close();
				} catch (IOException e) {
				}
			}
			if (inY != null) {
				try {
					inY.close();
				} catch (IOException e) {
				}
			}
			if (inZ != null) {
				try {
					inZ.close();
				} catch (IOException e) {
				}
			}
		}

		return dataEE1;
	}
}
