package nl.vu.psy.ams.suite.gui.drawing;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.geom.AffineTransform;
import java.awt.geom.Path2D;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.Arrays;

import nl.vu.psy.ams.suite.data.CurrentOpenData;
import nl.vu.psy.ams.suite.data.files.BinaryFile;
import nl.vu.psy.ams.suite.data.structures.file7fs.Ams7fsChannelInfo;
import nl.vu.psy.ams.suite.gui.axes.YAxis;
import nl.vu.psy.ams.suite.main.AppSettings;
import nl.vu.psy.ams.suite.main.AppSettings.Settings;
import nl.vu.psy.ams.suite.tools.Utils;
import nl.vu.psy.ams.suite.gui.graphs.overlays.Overlay;
import nl.vu.psy.ams.suite.gui.graphs.overlays.RespCycleOverlay;

/*
 * Draws binary 16-bit data from a signal extracted from
 * a 5fs file. Uses a buffer to make drawing faster, and loads
 * subset files generated by SubsetFileGenerator to draw even
 * faster.
 */
public class BinaryDataDrawer extends DataDrawer implements AutoCloseable {

	private int[] buffer, ticks;
	private int bufferSize;
	private int maxDisplayPoints;
	private long lBuffer, rBuffer;
	private long sampleTimeInUS;
	private long startTime;
	private long totalNumberOfShorts;

	private File baseFile;
	private int curSkip;
	private boolean isCalculating = true;

	private double[] av;

	private boolean drawAv = false;
	private boolean drawRaw = true;
	Ams7fsChannelInfo chan;
	private long lOffset;
	private long rOffset;

	private ByteBuffer bb;
	private IntBuffer buff;
	private boolean clipAtZero = false;
	private Color avColor = new Color(0, 128, 0);

	private double avLength = 10000000.;

	private boolean enabled = true;
	// private boolean drawSCL = false;
	// private boolean labelbased = false;
	private String channelName = "", tickFile = "";
	private boolean useTicks = false;
	private int nValues = 0;
	private boolean invert = false;
	// private boolean correctFilt = false; //to get Z0 and FILTDZ in the same range
	// on RSATab
	private ArrayList<Overlay> overlays = new ArrayList<Overlay>();
	private BinaryFile bf;
	private RandomAccessFile is = null;
	private long fl = 0;

	public BinaryDataDrawer(String name, String baseName, YAxis yAxis, Color color) {
		super(baseName, yAxis, color);
		maxDisplayPoints = AppSettings.getInstance().getIntProperty(Settings.MAXDISPLAYPOINTS);
		bufferSize = AppSettings.getInstance().getIntProperty(Settings.BINARYBUFFERSIZE);
		buffer = new int[bufferSize];
		ticks = new int[bufferSize];
		lBuffer = -1;
		rBuffer = -1;
		sampleTimeInUS = (int) CurrentOpenData.getInstance().getFileHeader().getDwSampleTime_us();
		try {
			chan = CurrentOpenData.getInstance().getChannelInfoFromID(name);
			sampleTimeInUS *= CurrentOpenData.getInstance().getChannelInfoFromID(name).getDwDivider();
			tickFile = chan.getTickFile();
			if (baseName.equals("FILTDZ")) {
				// chan = CurrentOpenData.getInstance().getChannelInfoFromID("FILTDZ");
				int nSkipped = (int) (100000 / CurrentOpenData.getInstance().getFileHeader().getDwSampleTime_us());
				// if (sampleTimeInUS < 100000) {
				// sampleTimeInUS = 100000;
				// }
				sampleTimeInUS *= nSkipped;
				tickFile = "TicksARed";
				// if (name == "Z0")
				// correctFilt = true;
			}
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		channelName = baseName;
		startTime = 1000L * CurrentOpenData.getInstance().getStarts().get(0).getDwClockTick_ms();
		baseFile = new File(CurrentOpenData.getInstance().getFilePath(), baseName + ".bin");
		curSkip = -1;
		bb = ByteBuffer.allocateDirect(bufferSize * 4);
		buff = bb.asIntBuffer();
		bf = new BinaryFile(baseName);
		File ticks = new File(CurrentOpenData.getInstance().getFilePath(), tickFile + ".bin");
		if (ticks.exists())
			try {
				is = new RandomAccessFile(ticks, "r");
				fl = is.length();
			} catch (IOException e) {
				e.printStackTrace();
			}
	}

	public BinaryDataDrawer(String name, YAxis yAxis) {
		this(name, yAxis, Color.BLACK);
	}

	public BinaryDataDrawer(String name, YAxis yAxis, Color color) {
		super(name, yAxis, color);
		maxDisplayPoints = AppSettings.getInstance().getIntProperty(Settings.MAXDISPLAYPOINTS);
		bufferSize = AppSettings.getInstance().getIntProperty(Settings.BINARYBUFFERSIZE);
		buffer = new int[bufferSize];
		ticks = new int[bufferSize];
		lBuffer = -1;
		rBuffer = -1;
		sampleTimeInUS = (int) CurrentOpenData.getInstance().getFileHeader().getDwSampleTime_us();
		try {
			chan = CurrentOpenData.getInstance().getChannelInfoFromID(name);
			sampleTimeInUS *= CurrentOpenData.getInstance().getChannelInfoFromID(name).getDwDivider();
			tickFile = chan.getTickFile();
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		startTime = 1000L * CurrentOpenData.getInstance().getStarts().get(0).getDwClockTick_ms();
		channelName = name;
		baseFile = new File(CurrentOpenData.getInstance().getFilePath(), name + ".bin");
		totalNumberOfShorts = baseFile.length() / 4;
		curSkip = -1;
		bb = ByteBuffer.allocateDirect(bufferSize * 4);
		buff = bb.asIntBuffer();
		bf = new BinaryFile(name);
		File ticks = new File(CurrentOpenData.getInstance().getFilePath(), tickFile + ".bin");
		if (ticks.exists())
			try {
				is = new RandomAccessFile(ticks, "r");
				fl = is.length();
			} catch (IOException e) {
				e.printStackTrace();
			}
	}

	@Override
	public void close() throws Exception {
		is.close();
	}

	public void connectOverlay(Overlay overlay) {
		overlays.add(overlay);
	}

	private void drawAv(Graphics2D g) {
		if (av == null)
			return;
		g.setColor(avColor);
		Stroke oldStroke = g.getStroke();
		g.setStroke(new BasicStroke(2));

		double leftTime = graph.getxAxis().getLeftTime();
		double rightTime = graph.getxAxis().getRightTime();

		int w = graph.getWidth();
		int h = graph.getHeight();

		AffineTransform at = new AffineTransform();
		at.scale(w / (rightTime - leftTime), -h / (yAxis.getTopValue() - yAxis.getBottomValue()));
		at.translate(-leftTime, -yAxis.getTopValue());

		int nPointsInPath = 0;
		double curTime = CurrentOpenData.getInstance().getStartTimeInUS() + avLength / 2;
		int n = av.length;
		Path2D.Double path = new Path2D.Double(Path2D.WIND_EVEN_ODD, n);
		int li = (int) ((leftTime - CurrentOpenData.getInstance().getStartTimeInUS()) / avLength);
		if (li < 0)
			li = 0;
		curTime += li * avLength;
		for (int i = li; i < n; i++) {
			if (curTime > rightTime + avLength)
				break;
			if (curTime > leftTime - avLength) {
				// double val = csi.splint(curTime);
				double val = av[i];
				if (clipAtZero && yAxis.getRealValueFromSampleValue(val) < 0)
					val = yAxis.getSampleValueFromRealValue(0);
				if (nPointsInPath == 0) {
					path.moveTo(curTime, val);
				} else {
					path.lineTo(curTime, val);
				}
				nPointsInPath++;
			}
			curTime += avLength;
		}
		if (nPointsInPath > 0) {
			path.transform(at);
			g.draw(path);
		}
		g.setStroke(oldStroke);
	}

	@Override
	public void drawData(Graphics2D g) {

		if (enabled == false)
			return;

		if (drawRaw)
			drawRaw(g);
		if (drawAv)
			drawAv(g);

		/*
		 * if(drawSCL){
		 * drawLegend(g);
		 * }
		 */
	}
	/*
	 * private void drawLegend(Graphics2D g) {
	 * 
	 * 
	 * 
	 * FontMetrics fm = g.getFontMetrics();
	 * int txtWidth = fm.stringWidth("Label Based Peak Detection");
	 * int txtH = fm.getMaxAscent();
	 * 
	 * if(isCalculating == false){
	 * g.setColor(Color.WHITE);
	 * g.fillRect(20, 20, 60 + txtWidth, 20);
	 * g.setColor(Color.BLACK);
	 * g.drawRect(20, 20, 60 + txtWidth, 20);
	 * 
	 * 
	 * Stroke oldStroke = g.getStroke();
	 * g.setStroke(new BasicStroke(2));
	 * g.setColor(Color.BLUE);
	 * g.drawLine(30, 30, 40, 30);
	 * g.drawLine(35, 25, 35, 35);
	 * g.setStroke(oldStroke);
	 * 
	 * 
	 * g.setColor(Color.BLACK);
	 * if(labelbased){
	 * g.drawString("Label based Design (SCL)", 70, 30 + txtH / 2);
	 * }else{
	 * g.drawString("Event based Design (SCR)", 70, 30 + txtH / 2);
	 * }
	 * }
	 * }
	 */

	private void drawRaw(Graphics2D g) {

		double leftTime = graph.getxAxis().getLeftTime();
		double rightTime = graph.getxAxis().getRightTime();
		double leftOffset = getOffsetFromTime(leftTime);
		double rightOffset = getOffsetFromTime(rightTime);
		lOffset = (long) Math.floor(leftOffset);
		rOffset = (long) Math.ceil(rightOffset) + 1;
		totalNumberOfShorts = baseFile.length() / 4;

		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (lOffset < 0)
			lOffset = 0;
		if (rOffset >= totalNumberOfShorts)
			rOffset = totalNumberOfShorts - 1;
		if (lOffset >= rOffset)
			return;

		int w = graph.getWidth();
		int h = graph.getHeight();

		Color oldColor = g.getColor();
		g.setColor(color);

		long nShorts = rOffset - lOffset;
		int skipNeeded = Utils.GetNextPowerOfTwo((int) (nShorts / maxDisplayPoints));
		if (skipNeeded == 0)
			skipNeeded = 1;
		if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip) {
			refillBuffer((rOffset + lOffset) / 2, skipNeeded);
		}

		if (isCalculating == true) {
			g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
			String calcText = "Calculating...";
			g.setFont(new Font("Arial", Font.BOLD, 20));
			FontMetrics met = g.getFontMetrics();
			Rectangle2D bounds = met.getStringBounds(calcText, g);
			g.drawString(calcText, (float) (graph.getWidth() / 2. - bounds.getWidth() / 2.),
					(float) (graph.getHeight() / 2. + bounds.getHeight() / 3.));
			return;
		}
		int curOffset = (int) ((lOffset - lBuffer) / curSkip);
		int nPoints = (int) (nShorts / curSkip);
		if (curOffset < 0 || nPoints > bufferSize) {
			skipNeeded += 1;
			refillBuffer((rOffset + lOffset) / 2, skipNeeded);
			// try {
			// Thread.sleep(100);
			// } catch (InterruptedException e) {
			// e.printStackTrace();
			// }
			curOffset = (int) ((lOffset - lBuffer) / curSkip);
			nPoints = (int) (nShorts / curSkip);
		}
		Path2D.Double path = new Path2D.Double(Path2D.WIND_EVEN_ODD, nPoints);
		long curFileOffset;
		/*
		 * if (useTicks) {
		 * curFileOffset = (( (long)ticks[curOffset]*1000L - startTime) /
		 * sampleTimeInUS);
		 * if (curFileOffset != lOffset) {
		 * long diff = curFileOffset - lOffset;
		 * lOffset -= diff;
		 * if (lOffset < 0)
		 * lOffset = 0;
		 * rOffset -= diff;
		 * if (rOffset >= totalNumberOfShorts)
		 * rOffset = totalNumberOfShorts - 1;
		 * midPoint = (rOffset + lOffset) / 2;
		 * if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip)
		 * refillBuffer(midPoint, skipNeeded);
		 * curOffset = (int) ((lOffset - lBuffer) / curSkip);
		 * curFileOffset = (( (long)ticks[curOffset]*1000L - startTime) /
		 * sampleTimeInUS);
		 * }
		 * curFileOffset = (( (long)ticks[curOffset]*1000L - startTime) /
		 * sampleTimeInUS);
		 * }
		 * else
		 */
		curFileOffset = lOffset;
		long prevTick = 0, curTick;
		if (useTicks)
			prevTick = (((long) ticks[curOffset] * 1000L - startTime) / sampleTimeInUS);
		// double wScale = w / (rightOffset - leftOffset);
		double wScale = w / ((rightTime - leftTime) / sampleTimeInUS);
		double av = 0;
		for (int i = 0; i < nPoints; i++) {
			if (i + curOffset >= bufferSize)
				break;
			av += buffer[curOffset + i];
		}
		av /= nPoints;
		double avC = 0;
		if (overlays.size() != 0) {
			for (Overlay ov : overlays) {
				if (ov instanceof RespCycleOverlay)
					ov.setAverage(av - this.average);
				else
					ov.setAverage(av);
			}
		}
		if (channelName == "FILTDZ" && overlays.size() != 0) {
			avC = av - this.average;
		}
		path.moveTo(curFileOffset, buffer[curOffset] - avC);
		for (int i = 1; i < nPoints; i++) {
			curOffset++;
			if (curOffset >= nValues) {
				// wScale = w / ((rightTime - leftTime) / sampleTimeInUS);
				break;
			}
			if (useTicks) {
				curTick = (((long) ticks[curOffset] * 1000L - startTime) / sampleTimeInUS);
				// if (curTick < prevTick)
				// System.out.println("Negative offset: " + (curTick - prevTick));
				curFileOffset += (curTick - prevTick);
				prevTick = curTick;
				// if (curFileOffset > rOffset)
				// break;
			} else
				curFileOffset += curSkip;
			path.lineTo(curFileOffset, buffer[curOffset] - avC);
		}
		// String d1 = Double.toString(rightOffset-leftOffset), d2 =
		// Double.toString((rightTime-leftTime) / sampleTimeInUS);
		// System.out.println(d1 + " " + d2);
		AffineTransform at = new AffineTransform();
		at.scale(wScale, -h / (yAxis.getTopValue() - yAxis.getBottomValue()));
		at.translate(-leftOffset, -yAxis.getTopValue());

		path.transform(at);

		g.draw(path);

		g.setColor(oldColor);
	}

	public Color getAvColor() {
		return avColor;
	}

	public double getAvLength() {
		return avLength;
	}

	public double[] getBounds() {
		return getBounds(false);
	}

	@Override
	public double[] getBounds(boolean forceDebugMinMax) {

		if (drawRaw) {
			double minValue = 0;
			double maxValue = 0;
			double[] retArray = new double[2];
			double leftTime = graph.getxAxis().getLeftTime();
			double rightTime = graph.getxAxis().getRightTime();
			double leftOffset = getOffsetFromTime(leftTime);
			double rightOffset = getOffsetFromTime(rightTime);
			lOffset = (long) Math.floor(leftOffset);
			rOffset = (long) Math.ceil(rightOffset) + 1;

			if (totalNumberOfShorts == 0)
				totalNumberOfShorts = baseFile.length() / 4;
			if (lOffset < 0)
				lOffset = 0;
			if (rOffset >= totalNumberOfShorts)
				rOffset = totalNumberOfShorts - 1;
			if (lOffset >= rOffset)
				return null;

			long nShorts = rOffset - lOffset;
			int skipNeeded = Utils.GetNextPowerOfTwo((int) (nShorts / maxDisplayPoints));
			if (skipNeeded == 0)
				skipNeeded = 1;
			if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip) {
				refillBuffer((rOffset + lOffset) / 2, skipNeeded);
				// try {
				// Thread.sleep(100);
				// } catch (InterruptedException e) {
				// e.printStackTrace();
				// }
			}
			if (isCalculating == true)
				return null;

			int lBufferOffset = (int) ((lOffset - lBuffer) / curSkip);
			int nPoints = (int) (nShorts / curSkip);
			if (lBufferOffset < 0 || nPoints > bufferSize) {
				skipNeeded += 1;
				refillBuffer((rOffset + lOffset) / 2, skipNeeded);
				// try {
				// Thread.sleep(100);
				// } catch (InterruptedException e) {
				// e.printStackTrace();
				// }
				lBufferOffset = (int) ((lOffset - lBuffer) / curSkip);
				nPoints = (int) (nShorts / curSkip);
			}
			int curOffset = lBufferOffset;
			double min = Double.NEGATIVE_INFINITY, max = Double.POSITIVE_INFINITY;
			double av = 0;
			for (int i = 0; i < nPoints; i++) {
				av += buffer[curOffset + i];
			}
			av /= nPoints;
			double avC = 0;
			if (overlays.size() != 0) {
				for (Overlay ov : overlays) {
					if (ov instanceof RespCycleOverlay)
						ov.setAverage(av - this.average);
					else
						ov.setAverage(av);
				}
			}
			if (channelName == "FILTDZ" && overlays.size() != 0) {
				avC = av - this.average;
			}
			if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 1) {
				int length = 0;
				double sum = 0.0, standardDeviation = 0.0;
				for (int i = 0; i < nPoints; i++) {
					if (curOffset >= bufferSize)
						break;
					sum += buffer[curOffset] - avC;
					length++;
					curOffset++;
				}
				curOffset = lBufferOffset;
				double mean = sum / length;
				for (int i = 0; i < nPoints; i++) {
					if (curOffset >= bufferSize)
						break;
					standardDeviation += Math.pow(buffer[curOffset] - avC - mean, 2);
					curOffset++;
				}
				standardDeviation = Math.sqrt(standardDeviation / length);
				curOffset = lBufferOffset;
				min = mean - 3 * standardDeviation;
				max = mean + 3 * standardDeviation;
			}
			if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 2) {
				int arrSize = nPoints / 100;
				if (arrSize > 500)
					arrSize = 500;
				if (arrSize > 0) {
					int[] highOnePercent = new int[arrSize];
					int[] lowOnePercent = new int[arrSize];
					for (int i = 0; i < arrSize; i++) {
						highOnePercent[i] = buffer[curOffset] - (int) avC;
						lowOnePercent[i] = buffer[curOffset] - (int) avC;
						curOffset++;
					}
					Arrays.sort(lowOnePercent);
					Arrays.sort(highOnePercent);
					for (int i = arrSize; i < nPoints; i++) {
						if (curOffset >= bufferSize)
							break;
						int val = buffer[curOffset] - (int) avC;
						if (val > highOnePercent[0]) {
							highOnePercent[0] = val;
							Arrays.sort(highOnePercent);
						}
						if (val < lowOnePercent[arrSize - 1]) {
							lowOnePercent[arrSize - 1] = val;
							Arrays.sort(lowOnePercent);
						}
						curOffset++;
					}
					curOffset = lBufferOffset;
					min = lowOnePercent[arrSize - 1];
					max = highOnePercent[0];
				} else if (nPoints > 0) {
					max = Double.NEGATIVE_INFINITY;
					min = Double.POSITIVE_INFINITY;
					double newValue;
					for (int i = 0; i < nPoints; i++) {
						if (curOffset >= bufferSize)
							break;
						newValue = buffer[curOffset];
						if (newValue < min)
							min = newValue;
						if (newValue > max)
							max = newValue;
						curOffset++;
					}
				}
			}
			if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 0) {
				max = Double.NEGATIVE_INFINITY;
				min = Double.POSITIVE_INFINITY;
				double newValue;
				for (int i = 0; i < nPoints; i++) {
					if (curOffset >= bufferSize)
						break;
					newValue = buffer[curOffset] - avC;
					if (newValue < min)
						min = newValue;
					if (newValue > max)
						max = newValue;
					curOffset++;
				}
			}
			retArray[0] = min;
			retArray[1] = max;

			if (CurrentOpenData.getInstance().isDebugFileexists() == true && forceDebugMinMax == true) {
				// JdH: always just use minValue and maxValue from VUDAMSDebug.json
				if (channelName.equals("ECG")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getECGMin());
					maxValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getECGMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("DZ")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getDZMin());
					maxValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getDZMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("DZDT")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getDZDTMin());
					maxValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getDZDTMax());

					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("Z0")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getZ0Min());
					maxValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getZ0Max());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("MXR") || channelName.equals("MYR") || channelName.equals("MZR")
						|| channelName.equals("XMT") || channelName.equals("YMT") || channelName.equals("ZMT")) {

					minValue = yAxis.getSampleValueFromRealValue(
							CurrentOpenData.getInstance().getDebugSettings().getMotilityXYZMin());
					maxValue = yAxis.getSampleValueFromRealValue(
							CurrentOpenData.getInstance().getDebugSettings().getMotilityXYZMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("MYA")) {
					minValue = yAxis.getSampleValueFromRealValue(
							CurrentOpenData.getInstance().getDebugSettings().getMotilityRawMin());
					maxValue = yAxis.getSampleValueFromRealValue(
							CurrentOpenData.getInstance().getDebugSettings().getMotilityRawMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("BAT")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getBATMin());
					maxValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getBATMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("SCL")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getSCLMin());
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getSCLMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
				if (channelName.equals("PCG")) {
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getPCGMin());
					minValue = yAxis
							.getSampleValueFromRealValue(CurrentOpenData.getInstance().getDebugSettings().getPCGMax());
					// if(retArray[0] < minValue){
					retArray[0] = minValue;
					// }
					// if(retArray[1] > maxValue){
					retArray[1] = maxValue;
					// }
				}
			}
			return retArray;
		} else if (drawAv && av != null) {
			double[] retArray = new double[2];
			double leftTime = graph.getxAxis().getLeftTime();
			double rightTime = graph.getxAxis().getRightTime();
			double min = Double.NEGATIVE_INFINITY, max = Double.POSITIVE_INFINITY;
			double curTime = CurrentOpenData.getInstance().getStartTimeInUS() + avLength / 2;
			int n = av.length;
			if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 1) {
				int length = 0;
				double sum = 0.0, standardDeviation = 0.0;
				for (int i = 0; i < n; i++) {
					if (curTime > rightTime + avLength)
						break;
					if (curTime > leftTime - avLength) {
						sum += av[i];
						length++;
					}
					curTime += avLength;
				}
				curTime = CurrentOpenData.getInstance().getStartTimeInUS() + avLength / 2;
				double mean = sum / length;
				for (int i = 0; i < n; i++) {
					if (curTime > rightTime + avLength)
						break;
					if (curTime > leftTime - avLength) {
						standardDeviation += Math.pow(av[i] - mean, 2);
					}
					curTime += avLength;
				}
				standardDeviation = Math.sqrt(standardDeviation / length);
				curTime = CurrentOpenData.getInstance().getStartTimeInUS() + avLength / 2;
				min = mean - 3 * standardDeviation;
				max = mean + 3 * standardDeviation;
			}
			if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 2) {
				double nPoints = (rightTime - leftTime) / avLength;
				int arrSize = (int) nPoints / 100;
				if (arrSize > 500)
					arrSize = 500;
				if (arrSize > 0) {
					double[] highOnePercent = new double[arrSize];
					double[] lowOnePercent = new double[arrSize];
					for (int i = 0; i < arrSize; i++) {
						highOnePercent[i] = av[i];
						lowOnePercent[i] = av[i];
						curTime += avLength;
					}
					Arrays.sort(lowOnePercent);
					Arrays.sort(highOnePercent);
					for (int i = arrSize; i < n; i++) {
						if (curTime > rightTime + avLength)
							break;
						double val = av[i];
						if (curTime > leftTime - avLength) {
							if (val > highOnePercent[0]) {
								highOnePercent[0] = val;
								Arrays.sort(highOnePercent);
							}
							if (val < lowOnePercent[arrSize - 1]) {
								lowOnePercent[arrSize - 1] = val;
								Arrays.sort(lowOnePercent);
							}
						}
						curTime += avLength;
					}
					curTime = CurrentOpenData.getInstance().getStartTimeInUS() + avLength / 2;
					min = lowOnePercent[arrSize - 1];
					max = highOnePercent[0];
				} else if (nPoints > 0) {
					max = Double.NEGATIVE_INFINITY;
					min = Double.POSITIVE_INFINITY;
					for (int i = 0; i < n; i++) {
						if (curTime > rightTime + avLength)
							break;
						if (curTime > leftTime - avLength) {
							if (av[i] < min)
								min = av[i];
							if (av[i] > max)
								max = av[i];
						}
						curTime += avLength;
					}
				}
			}
			if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 0) {
				max = Double.NEGATIVE_INFINITY;
				min = Double.POSITIVE_INFINITY;
				for (int i = 0; i < n; i++) {
					if (curTime > rightTime + avLength)
						break;
					if (curTime > leftTime - avLength) {
						if (av[i] < min)
							min = av[i];
						if (av[i] > max)
							max = av[i];
					}
					curTime += avLength;
				}
			}
			retArray[0] = min;
			retArray[1] = max;
			return retArray;
		}
		return null;
	}

	private double getOffsetFromTime(double time) {
		if (useTicks) {
			long offset = (long) Math.floor((time - startTime) / sampleTimeInUS);
			int sampleTimeinMS = (int) sampleTimeInUS / 1000;
			long tick, diff, oldOffset = offset;
			long startTime = CurrentOpenData.getInstance().getStarts().get(0).getDwClockTick_ms();
			try {
				long len = fl / 4;
				if (offset > len - 1)
					offset = len - 1;
				if (offset < 0)
					offset = 0;
				is.seek(4 * offset);
				// System.out.println(offset + " " + len);
				tick = (is.readInt() - startTime) / sampleTimeinMS;
				diff = tick - offset;
				offset -= diff;
				long diff2 = tick - oldOffset;
				if (Math.abs(diff) < 100000) {
					int loopCount = 0; // , div = 2;
					while (Math.abs(diff2) > 1 && loopCount < 1000) {
						if (offset < 0 || 4 * offset >= fl) {
							break;
						}
						is.seek(4 * offset);
						tick = (is.readInt() - startTime) / sampleTimeinMS;
						diff2 = tick - oldOffset;
						offset -= diff2;
						loopCount++;
					}
					if (loopCount > 2)
						System.out.println("correct ticks bdrawer: " + loopCount + " " + diff);
				} else {
					// binary search
					long low = 0, high = len - 1, mid = 0;
					while (low <= high) {
						mid = low + (high - low) / 2;
						is.seek(4 * mid);
						tick = (is.readInt() - startTime) / sampleTimeinMS;

						if (tick == oldOffset) {
							offset = mid;
							break;
						} else if (tick < oldOffset)
							low = mid + 1;

						else
							high = mid - 1;
					}
					if (tick != oldOffset) { // not found
						if (low < 0)
							low = 0;
						if (low > len - 1)
							low = len - 1;
						is.seek(4 * low);
						long tick1 = (is.readInt() - startTime) / sampleTimeinMS;
						if (high < 0)
							high = 0;
						if (high > len - 1)
							high = len - 1;
						is.seek(4 * high);
						long tick2 = (is.readInt() - startTime) / sampleTimeinMS;
						if (oldOffset - tick1 < tick2 - oldOffset)
							offset = low;
						else
							offset = high;
					}
					System.out.println("binary search bdrawer: " + diff);
				}
				if (offset < 0)
					offset = 0;
				if (offset >= fl)
					offset = fl - 1;
			} catch (IOException e) {
				e.printStackTrace();
			}
			return offset;
		} else
			return ((time - startTime) / sampleTimeInUS);
	}

	@Override
	public double getValueAtTime(double time) {
		long offset = Math.round(getOffsetFromTime(time));
		int bufferOffset;
		if (offset < lBuffer || offset > rBuffer)
			refillBuffer(offset, curSkip);
		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (offset < 0 || offset >= totalNumberOfShorts)
			return Integer.MAX_VALUE;
		bufferOffset = (int) ((offset - lBuffer) / curSkip);
		if (bufferOffset < 0 || bufferOffset > nValues)
			return Integer.MAX_VALUE;
		// if (channelName == "ECG" || channelName == "V2ecg")
		// if (buffer[bufferOffset - 1] > buffer[bufferOffset] || buffer[bufferOffset +
		// 1] > buffer[bufferOffset])
		// System.out.println("Warning: R peak incorrect!");
		return buffer[bufferOffset];
	}

	public double[] getValuesBetweenTimes(double lTime, double rTime) {
		double lOff = getOffsetFromTime(lTime);
		double rOff = getOffsetFromTime(rTime);
		long loffset = (long) Math.ceil(lOff);
		long roffset = (long) Math.floor(rOff);
		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (loffset < 0 || loffset >= totalNumberOfShorts)
			return null;
		if (roffset < 0 || roffset >= totalNumberOfShorts)
			return null;
		int lbO = (int) ((loffset - lBuffer) / curSkip);
		int rbO = (int) ((roffset - lBuffer) / curSkip);
		if (lbO < 0 || lbO > buffer.length)
			return null;
		if (rbO < 0 || rbO > buffer.length)
			return null;
		int n = 2 * (rbO - lbO + 1);
		if (n < 1)
			return null;
		double[] ret = new double[n];
		int ind = 0;
		for (int i = lbO; i <= rbO; i++) {
			ret[ind] = lTime + (i * curSkip + lBuffer - lOff) * sampleTimeInUS;
			ind++;
			ret[ind] = buffer[i];
			ind++;
		}
		return ret;
	}

	public boolean isEnabled() {
		return enabled;
	}

	private void recalcAverage() {
		if (sampleTimeInUS > avLength / 10)
			return;
		FileChannel fc = null;
		FileInputStream fis = null;
		int curIndex = 0;
		try {
			fis = new FileInputStream(baseFile);
			fc = fis.getChannel();
			ByteBuffer bb = ByteBuffer.allocate(1000000);
			IntBuffer sb = bb.asIntBuffer();
			long fs = baseFile.length();
			int nRead = 0;
			int nSRead;
			int[] buffer = new int[bb.limit() / 4];
			double curSum = 0;
			int nInSum = 0;
			int nIn60Sec = (int) (avLength / sampleTimeInUS);
			av = new double[(int) Math.ceil((double) fs / (2 * nIn60Sec))];

			for (long i = 0; i < fs; i += nRead) {
				bb.clear();
				sb.clear();
				nRead = fc.read(bb);
				nSRead = nRead / 4;
				if (nRead < 1)
					break;
				sb.get(buffer, 0, nSRead);
				for (int j = 0; j < nSRead; j++) {
					curSum += buffer[j];
					nInSum++;
					if (nInSum == nIn60Sec) {
						av[curIndex] = curSum / nInSum;
						curIndex++;
						curSum = 0;
						nInSum = 0;
					}
				}
			}
			if (nInSum > 0) {
				av[curIndex] = curSum / nInSum;
				curIndex++;
				curSum = 0;
				nInSum = 0;
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (fc != null) {
				try {
					fc.close();
					fis.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}

		double curTime = CurrentOpenData.getInstance().getStartTimeInUS() + avLength / 2;

		double xAr[] = new double[av.length];
		for (int i = 0; i < av.length; i++) {
			xAr[i] = curTime + i * avLength;
		}

	}

	private void refillBuffer(long midPoint, int skipNeeded) {
		totalNumberOfShorts = baseFile.length() / 4;
		long lPos = midPoint - skipNeeded * bufferSize / 2;
		if (lPos < 0)
			lPos = 0;
		long rPos = lPos + bufferSize * skipNeeded;
		totalNumberOfShorts = baseFile.length() / 4;
		if (rPos >= totalNumberOfShorts) {
			rPos = totalNumberOfShorts - 1;
			lPos = rPos - bufferSize * skipNeeded;
			if (lPos < 0)
				lPos = 0;
		}
		nValues = (int) ((rPos - lPos) / skipNeeded);

		File dataFile, fileTicks;
		if (skipNeeded == 1) {
			dataFile = baseFile;
			fileTicks = new File(CurrentOpenData.getInstance().getFilePath(), tickFile + ".bin");
		} else {
			dataFile = new File(new File(baseFile.getParentFile(), "tmp"), name + ".bin-" + skipNeeded);
			fileTicks = new File(new File(baseFile.getParentFile(), "tmp"), tickFile + ".bin-" + skipNeeded);
		}
		if (dataFile.exists()) {
			FileChannel fc = null;
			FileInputStream fis = null;
			try {
				fis = new FileInputStream(dataFile);
				fc = fis.getChannel();
				bb.clear();
				bb.limit(4 * nValues);
				fc.read(bb, (long) (4 * Math.floor(lPos / skipNeeded)));
				buff.clear();
				fc.close();
				fis.close();
				buff.get(buffer, 0, nValues);
				if (isInvert())
					for (int i = 0; i < nValues; i++)
						buffer[i] *= -1;
				if (fileTicks.exists()) {
					fis = new FileInputStream(fileTicks);
					fc = fis.getChannel();
					bb.clear();
					bb.limit(4 * nValues);
					fc.read(bb, (long) (4 * Math.floor(lPos / skipNeeded)));
					buff.clear();
					buff.get(ticks, 0, nValues);
					useTicks = true;
				} else {
					useTicks = false;
				}
			} catch (IOException e) {

			} finally {
				if (fc != null) {
					try {
						fc.close();
						fis.close();
					} catch (IOException e) {
						e.printStackTrace();
					}
				}
			}
			isCalculating = false;
			curSkip = skipNeeded;
			lBuffer = lPos;
			rBuffer = rPos;
			if (lPos < lBuffer || rPos > rBuffer)
				System.out.println("Problem refill buffer BinaryDataDrawer");
		} else {
			for (int i = 0; i < nValues; i++)
				buffer[i] = Integer.MIN_VALUE;
			isCalculating = true;
			curSkip = 1;
			lBuffer = -1;
			rBuffer = -1;
			nValues = 0;
		}
	}

	public void setAvColor(Color col) {
		this.avColor = col;
	}

	public void setAvLength(double newLength) {
		avLength = newLength;
		recalcAverage();
		if (graph != null)
			graph.repaint();
	}

	public void setClipAtZero(boolean clip) {
		this.clipAtZero = clip;
	}

	public void setDrawAv(boolean drawAv) {
		this.drawAv = drawAv;
		if (drawAv == true)
			recalcAverage();
	}

	public void setDrawRaw(boolean drawRaw) {
		this.drawRaw = drawRaw;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public boolean isInvert() {
		return invert;
	}

	public void setInvert(boolean invert) {
		this.invert = invert;
	}

	public double getAverageBetweenTimes(double lTime, double rTime) {
		return bf.getAverageBetweenTimes(lTime, rTime);
	}

	public double getStdDevBetweenTimes(double lTime, double rTime) {
		return bf.getStdDevBetweenTimes(lTime, rTime);
	}
}
