package nl.vu.psy.ams.suite.gui.drawing;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.awt.geom.Path2D;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.channels.FileChannel;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import nl.vu.psy.ams.suite.data.CurrentOpenData;
import nl.vu.psy.ams.suite.data.structures.file7fs.Ams7fsChannelInfo;
import nl.vu.psy.ams.suite.gui.axes.YAxis;
import nl.vu.psy.ams.suite.main.AppSettings;
import nl.vu.psy.ams.suite.main.AppSettings.Settings;
import nl.vu.psy.ams.suite.tools.Utils;

import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;

/*
 * Draws binary 16-bit data from a signal extracted from
 * a 5fs/7fs file. Uses a buffer to make drawing faster, and loads
 * subset files generated by SubsetFileGenerator to draw even
 * faster. Calculates real values based on a formula instead of
 * on slope/intercept.
 */
public class FormulaDrawer extends DataDrawer implements AutoCloseable {

	double[] values;
	private int bufferSize;
	private int maxDisplayPoints;
	private long lBuffer, rBuffer;
	private long sampleTimeInUS;
	private int nValues;
	private long startTime;
	private long totalNumberOfShorts;
	private File baseFile;
	private int curSkip;
	private boolean isCalculating = true;
	Ams7fsChannelInfo chan;
	private long lOffset;
	private long rOffset;
	private int[] buffer, ticks;
	private ByteBuffer bb;
	private IntBuffer buff;
	private YAxis yAxis;
	private boolean useTicks = false;
	private boolean isFiltered = false;
	private String tickFile;
	private RandomAccessFile is = null;
	private long fl = 0;

	public FormulaDrawer(String name, YAxis yAxis) {
		super(name, yAxis);
		bufferSize = AppSettings.getInstance().getIntProperty(Settings.BINARYBUFFERSIZE);
		maxDisplayPoints = AppSettings.getInstance().getIntProperty(Settings.MAXDISPLAYPOINTS);
		buffer = new int[bufferSize];
		values = new double[bufferSize];
		ticks = new int[bufferSize];
		lBuffer = -1;
		rBuffer = -1;
		sampleTimeInUS = (int) CurrentOpenData.getInstance().getFileHeader().getDwSampleTime_us();
		try {
			chan = CurrentOpenData.getInstance().getChannelInfoFromID(name);
			sampleTimeInUS *= CurrentOpenData.getInstance().getChannelInfoFromID(name).getDwDivider();
			tickFile = chan.getTickFile();
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		startTime = 1000L * CurrentOpenData.getInstance().getStarts().get(0).getDwClockTick_ms();
		baseFile = new File(CurrentOpenData.getInstance().getFilePath(), name + ".bin");
		totalNumberOfShorts = baseFile.length() / 4;
		curSkip = -1;
		bb = ByteBuffer.allocateDirect(bufferSize * 4);
		buff = bb.asIntBuffer();
		this.yAxis = yAxis;
		try {
			is = new RandomAccessFile(new File(CurrentOpenData.getInstance().getFilePath(), tickFile + ".bin"),
					"r");
			fl = is.length();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public FormulaDrawer(String name, String baseName, YAxis yAxis, Color color) {
		super(name, yAxis, color);
		bufferSize = AppSettings.getInstance().getIntProperty(Settings.BINARYBUFFERSIZE);
		maxDisplayPoints = AppSettings.getInstance().getIntProperty(Settings.MAXDISPLAYPOINTS);
		buffer = new int[bufferSize];
		values = new double[bufferSize];
		ticks = new int[bufferSize];
		lBuffer = -1;
		rBuffer = -1;
		sampleTimeInUS = (int) CurrentOpenData.getInstance().getFileHeader().getDwSampleTime_us();
		try {
			chan = CurrentOpenData.getInstance().getChannelInfoFromID(name);
			sampleTimeInUS *= CurrentOpenData.getInstance().getChannelInfoFromID(name).getDwDivider();
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		startTime = 1000L * CurrentOpenData.getInstance().getStarts().get(0).getDwClockTick_ms();
		baseFile = new File(CurrentOpenData.getInstance().getFilePath(), baseName + ".bin");
		isFiltered = true;
		totalNumberOfShorts = baseFile.length() / 4;
		curSkip = -1;
		bb = ByteBuffer.allocateDirect(bufferSize * 4);
		buff = bb.asIntBuffer();
		this.yAxis = yAxis;
		try {
			is = new RandomAccessFile(new File(CurrentOpenData.getInstance().getFilePath(), tickFile + ".bin"),
					"r");
			fl = is.length();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	@Override
	public void close() throws Exception {
		is.close();
	}

	@Override
	public void drawData(Graphics2D g) {
		double leftTime = graph.getxAxis().getLeftTime();
		double rightTime = graph.getxAxis().getRightTime();
		double leftOffset = getOffsetFromTime(leftTime);
		double rightOffset = getOffsetFromTime(rightTime);
		lOffset = (long) Math.floor(leftOffset);
		rOffset = (long) Math.ceil(rightOffset) + 1;

		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (lOffset < 0)
			lOffset = 0;
		if (rOffset >= totalNumberOfShorts)
			rOffset = totalNumberOfShorts - 1;
		if (lOffset >= rOffset)
			return;

		int w = graph.getWidth();
		int h = graph.getHeight();

		AffineTransform at = new AffineTransform();
		at.scale(w / (rightOffset - leftOffset), -h / (yAxis.getTopValue() - yAxis.getBottomValue()));
		at.translate(-leftOffset, -yAxis.getTopValue());

		Color oldColor = g.getColor();
		g.setColor(color);

		long nShorts = rOffset - lOffset;
		int skipNeeded = Utils.GetNextPowerOfTwo((int) (nShorts / maxDisplayPoints));
		if (skipNeeded == 0)
			skipNeeded = 1;
		if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip) {
			refillBuffer((rOffset + lOffset) / 2, skipNeeded);
		}

		if (isCalculating == true) {
			g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
			String calcText = "Calculating...";
			g.setFont(new Font("Arial", Font.BOLD, 20));
			FontMetrics met = g.getFontMetrics();
			Rectangle2D bounds = met.getStringBounds(calcText, g);
			g.drawString(calcText, (float) (graph.getWidth() / 2. - bounds.getWidth() / 2.),
					(float) (graph.getHeight() / 2. + bounds.getHeight() / 3.));
			return;
		}
		// int lBufferOffset = (int) ((lOffset - lBuffer) / curSkip);
		// int nPoints = (int) (nShorts / curSkip);
		// Path2D.Double path = new Path2D.Double(Path2D.WIND_EVEN_ODD, nPoints);
		// int curOffset = lBufferOffset;
		// long curFileOffset;
		// if (useTicks) {
		// curFileOffset = (((long) ticks[curOffset] * 1000L - startTime) /
		// sampleTimeInUS);
		// if (curFileOffset != lOffset) {
		// long diff = lOffset - curFileOffset;
		// lOffset -= diff;
		// if (lOffset < 0)
		// lOffset = 0;
		// rOffset -= diff;
		// long midPoint = (rOffset + lOffset) / 2;
		// if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip)
		// refillBuffer(midPoint - lOffset + curFileOffset, skipNeeded);
		// curOffset = (int) ((lOffset - lBuffer) / curSkip);
		// curFileOffset = (((long) ticks[curOffset] * 1000L - startTime) /
		// sampleTimeInUS);
		// }
		// } else
		// curFileOffset = lOffset;
		// path.moveTo(curFileOffset, values[curOffset]);
		// for (int i = 1; i < nPoints; i++) {
		// curOffset++;
		// if (useTicks)
		// curFileOffset = (((long) ticks[curOffset] * 1000L - startTime) /
		// sampleTimeInUS);
		// else
		// curFileOffset += curSkip;
		// path.lineTo(curFileOffset, values[curOffset]);
		// }
		int curOffset = (int) ((lOffset - lBuffer) / curSkip);
		int nPoints = (int) (nShorts / curSkip);
		Path2D.Double path = new Path2D.Double(Path2D.WIND_EVEN_ODD, nPoints);
		long curFileOffset;
		curFileOffset = lOffset;
		long prevTick = 0, curTick;
		if (useTicks)
			prevTick = (((long) ticks[curOffset] * 1000L - startTime) / sampleTimeInUS);
		path.moveTo(curFileOffset, values[curOffset]);
		for (int i = 1; i < nPoints; i++) {
			curOffset++;
			if (curOffset >= nValues) {
				// wScale = w / ((rightTime - leftTime) / sampleTimeInUS);
				break;
			}
			if (useTicks) {
				curTick = (((long) ticks[curOffset] * 1000L - startTime) / sampleTimeInUS);
				curFileOffset += (curTick - prevTick);
				prevTick = curTick;
				// if (curFileOffset > rOffset)
				// break;
			} else
				curFileOffset += curSkip;
			path.lineTo(curFileOffset, values[curOffset]);
		}

		path.transform(at);

		g.draw(path);
		g.setColor(oldColor);
	}

	@Override
	public double[] getBounds() {
		double[] retArray = new double[2];
		double leftTime = graph.getxAxis().getLeftTime();
		double rightTime = graph.getxAxis().getRightTime();
		double leftOffset = getOffsetFromTime(leftTime);
		double rightOffset = getOffsetFromTime(rightTime);
		long lOffset = (long) Math.floor(leftOffset);
		long rOffset = (long) Math.ceil(rightOffset) + 1;

		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (lOffset < 0)
			lOffset = 0;
		if (rOffset >= totalNumberOfShorts)
			rOffset = totalNumberOfShorts - 1;
		if (lOffset >= rOffset)
			return null;

		long nShorts = rOffset - lOffset;
		int skipNeeded = Utils.GetNextPowerOfTwo((int) (nShorts / maxDisplayPoints));
		if (skipNeeded == 0)
			skipNeeded = 1;
		if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip) {
			refillBuffer((rOffset + lOffset) / 2, skipNeeded);
		}
		if (isCalculating == true)
			return null;

		int lBufferOffset = (int) ((lOffset - lBuffer) / curSkip);
		int nPoints = (int) (nShorts / curSkip);
		int curOffset = lBufferOffset;
		double min = Double.NEGATIVE_INFINITY, max = Double.POSITIVE_INFINITY;
		if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 1) {
			int length = 0;
			double sum = 0.0, standardDeviation = 0.0;
			for (int i = 0; i < nPoints; i++) {
				if (curOffset >= bufferSize)
					break;
				sum += values[curOffset];
				length++;
				curOffset++;
			}
			curOffset = lBufferOffset;
			double mean = sum / length;
			for (int i = 0; i < nPoints; i++) {
				if (curOffset >= bufferSize)
					break;
				standardDeviation += Math.pow((double) values[curOffset] - mean, 2);
				curOffset++;
			}
			standardDeviation = Math.sqrt(standardDeviation / length);
			curOffset = lBufferOffset;
			min = mean - 3 * standardDeviation;
			max = mean + 3 * standardDeviation;
		}
		if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 2) {
			int arrSize = nPoints / 100;
			if (arrSize > 500)
				arrSize = 500;
			if (arrSize > 0) {
				double[] highOnePercent = new double[arrSize];
				double[] lowOnePercent = new double[arrSize];
				for (int i = 0; i < arrSize; i++) {
					highOnePercent[i] = values[curOffset];
					lowOnePercent[i] = values[curOffset];
					curOffset++;
				}
				Arrays.sort(lowOnePercent);
				Arrays.sort(highOnePercent);
				for (int i = arrSize; i < nPoints; i++) {
					if (curOffset >= bufferSize)
						break;
					double val = values[curOffset];
					if (val > highOnePercent[0]) {
						highOnePercent[0] = val;
						Arrays.sort(highOnePercent);
					}
					if (val < lowOnePercent[arrSize - 1]) {
						lowOnePercent[arrSize - 1] = val;
						Arrays.sort(lowOnePercent);
					}
					curOffset++;
				}
				curOffset = lBufferOffset;
				min = lowOnePercent[arrSize - 1];
				max = highOnePercent[0];
			}
		}
		if (AppSettings.getInstance().getIntPropertyOrToBeSaved(Settings.OUTLIERREMOVAL) == 0) {
			max = Double.NEGATIVE_INFINITY;
			min = Double.POSITIVE_INFINITY;
			curOffset = lBufferOffset;
			double newValue;
			for (int i = 0; i < nPoints; i++) {
				newValue = values[curOffset];
				if (newValue < min)
					min = newValue;
				if (newValue > max)
					max = newValue;
				curOffset++;
			}
		}
		retArray[0] = min;
		retArray[1] = max;
		return retArray;
	}

	private double getOffsetFromTime(double time) {
		if (useTicks) {
			long offset = (long) Math.floor((time - startTime) / sampleTimeInUS);
			int sampleTimeinMS = (int) sampleTimeInUS / 1000;
			long tick, diff, oldOffset = offset;
			long startTime = CurrentOpenData.getInstance().getStarts().get(0).getDwClockTick_ms();
			try {
				long len = fl / 4;
				if (offset > len - 1)
					offset = len - 1;
				if (offset < 0)
					offset = 0;
				is.seek(4 * offset);
				// System.out.println(offset + " " + len);
				tick = (is.readInt() - startTime) / sampleTimeinMS;
				diff = tick - offset;
				offset -= diff;
				long diff2 = tick - oldOffset;
				if (Math.abs(diff) < 100000) {
					int loopCount = 0; // , div = 2;
					while (Math.abs(diff2) > sampleTimeinMS && loopCount < 1000) {
						if (offset < 0 || 4 * offset >= fl) {
							break;
						}
						is.seek(4 * offset);
						tick = (is.readInt() - startTime) / sampleTimeinMS;
						diff2 = tick - oldOffset;
						offset -= diff2;
						loopCount++;
					}
					if (loopCount > 2)
						System.out.println("correct ticks fdrawer: " + loopCount + " " + diff);
				} else {
					// binary search
					long low = 0, high = len - 1, mid = 0;
					while (low <= high) {
						mid = low + (high - low) / 2;
						is.seek(4 * mid);
						tick = (is.readInt() - startTime) / sampleTimeinMS;

						if (tick == oldOffset) {
							offset = mid;
							break;
						} else if (tick < oldOffset)
							low = mid + 1;

						else
							high = mid - 1;
					}
					if (tick != oldOffset) { // not found
						if (low < 0)
							low = 0;
						if (low > len - 1)
							low = len - 1;
						is.seek(4 * low);
						long tick1 = (is.readInt() - startTime) / sampleTimeinMS;
						if (high < 0)
							high = 0;
						if (high > len - 1)
							high = len - 1;
						is.seek(4 * high);
						long tick2 = (is.readInt() - startTime) / sampleTimeinMS;
						if (oldOffset - tick1 < tick2 - oldOffset)
							offset = low;
						else
							offset = high;
					}
					System.out.println("binary search fdrawer: " + diff);
				}
				if (offset < 0)
					offset = 0;
				if (offset >= fl)
					offset = fl - 1;
			} catch (IOException e) {
				e.printStackTrace();
			}
			return offset;
		} else
			return ((time - startTime) / sampleTimeInUS);
	}

	private void refillBuffer(long midPoint, int skipNeeded) {
		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		long lPos = midPoint - skipNeeded * bufferSize / 2;
		if (lPos < 0)
			lPos = 0;
		long rPos = lPos + bufferSize * skipNeeded;
		if (rPos >= totalNumberOfShorts) {
			rPos = totalNumberOfShorts - 1;
			lPos = rPos - bufferSize * skipNeeded;
			if (lPos < 0)
				lPos = 0;
		}
		nValues = (int) ((rPos - lPos) / skipNeeded);

		File dataFile, fileT, fileTicks;
		if (skipNeeded == 1) {
			dataFile = baseFile;
			fileTicks = new File(CurrentOpenData.getInstance().getFilePath(), tickFile + ".bin");
			if (isFiltered)
				fileT = new File(CurrentOpenData.getInstance().getFilePath(), "FILTT_sc.bin");
			else
				fileT = new File(CurrentOpenData.getInstance().getFilePath(), "T_sc.bin");
		} else {
			dataFile = new File(new File(baseFile.getParentFile(), "tmp"), name + ".bin-" + skipNeeded);
			fileTicks = new File(new File(baseFile.getParentFile(), "tmp"), tickFile + ".bin-" + skipNeeded);
			if (isFiltered)
				fileT = new File(new File(baseFile.getParentFile(), "tmp"), "FILTT_sc.bin-" + skipNeeded);
			else
				fileT = new File(new File(baseFile.getParentFile(), "tmp"), "T_sc.bin-" + skipNeeded);
		}
		if (dataFile.exists()) {
			FileChannel fc = null;
			FileInputStream fis = null;
			try {
				fis = new FileInputStream(dataFile);
				fc = fis.getChannel();
				bb.clear();
				bb.limit(4 * nValues);
				fc.read(bb, (long) (4 * Math.floor(lPos / skipNeeded)));
				buff.clear();
				fc.close();
				fis.close();
				buff.get(buffer, 0, nValues);
				int[] bufferT = new int[bufferSize];
				if (chan.getSzID().equals("P_sc")) {
					if (fileT.exists()) {
						fis = new FileInputStream(fileT);
						fc = fis.getChannel();
						bb.clear();
						bb.limit(4 * nValues);
						fc.read(bb, (long) (4 * Math.floor(lPos / skipNeeded)));
						buff.clear();
						buff.get(bufferT, 0, nValues);
						fc.close();
						fis.close();
					}
				}
				calcValues(bufferT);
				if (fileTicks.exists()) {
					fis = new FileInputStream(fileTicks);
					fc = fis.getChannel();
					bb.clear();
					bb.limit(4 * nValues);
					fc.read(bb, (long) (4 * Math.floor(lPos / skipNeeded)));
					buff.clear();
					buff.get(ticks, 0, nValues);
					useTicks = true;
				}
			} catch (IOException e) {

			} finally {
				if (fc != null) {
					try {
						fc.close();
						fis.close();
					} catch (IOException e) {
						e.printStackTrace();
					}
				}
			}
			isCalculating = false;
			curSkip = skipNeeded;
			lBuffer = lPos;
			rBuffer = rPos;
		} else {
			for (int i = 0; i < nValues; i++)
				buffer[i] = Integer.MIN_VALUE;
			isCalculating = true;
			curSkip = 1;
			lBuffer = -1;
			rBuffer = -1;
		}

	}

	public void calcValues(int[] bufferT) {
		Set<String> variables = new HashSet<String>(chan.getConstants().keySet());
		if (chan.getSzID().equals("SCL"))
			variables.add("ch4");
		else
			variables.add(chan.getSzID());
		if (chan.getSzID().equals("P_sc"))
			variables.add("T_sc");
		Expression e = new ExpressionBuilder(chan.getFormula()).variables(variables).build()
				.setVariables(chan.getConstants());
		if (chan.getSzID().equals("P_sc")) {
			Ams7fsChannelInfo chanT;
			try {
				chanT = CurrentOpenData.getInstance().getChannelInfoFromID("T_sc");
				for (int i = 0; i < bufferSize; i++) {
					double val = buffer[i] * chan.getRealSlope();
					double valT = bufferT[i] * chanT.getRealSlope();
					e.setVariable("P_sc", val);
					e.setVariable("T_sc", valT);
					values[i] = e.evaluate();
				}
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		} else if (chan.getSzID().equals("SCL")) {
			for (int i = 0; i < bufferSize; i++) {
				double val = buffer[i];
				e.setVariable("ch4", val);
				values[i] = e.evaluate();
			}
		} else {
			for (int i = 0; i < bufferSize; i++) {
				double val = buffer[i] * chan.getRealSlope();
				e.setVariable(chan.getSzID(), val);
				values[i] = e.evaluate();
			}
		}
	}

	public void resetValues() {
		int nValues = (int) (baseFile.length() / 4);
		Set<String> variables = new HashSet<String>(chan.getConstants().keySet());
		variables.add(chan.getSzID());
		if (chan.getSzID().equals("P_sc"))
			variables.add("T_sc");
		Expression e = new ExpressionBuilder(chan.getFormula()).variables(variables).build()
				.setVariables(chan.getConstants());

		bb = ByteBuffer.allocateDirect(nValues * 4);
		buff = bb.asIntBuffer();
		buffer = new int[nValues];
		values = new double[nValues];

		if (baseFile.exists()) {
			FileChannel fc = null;
			FileInputStream fis = null;
			try {
				fis = new FileInputStream(baseFile);
				fc = fis.getChannel();
				bb.clear();
				bb.limit(4 * nValues);
				fc.read(bb, 0);
				buff.clear();
				buff.get(buffer, 0, nValues);
			} catch (IOException ef) {

			} finally {
				if (fc != null) {
					try {
						fc.close();
						fis.close();
					} catch (IOException ef) {
						ef.printStackTrace();
					}
				}
			}
		} else {
			for (int i = 0; i < nValues; i++)
				buffer[i] = Integer.MIN_VALUE;
		}
		if (chan.getSzID().equals("P_sc")) {
			File fileT = new File(CurrentOpenData.getInstance().getFilePath(), "T_sc.bin");
			bb.clear();
			int[] bufferT = new int[nValues];
			values = new double[nValues];

			if (fileT.exists()) {
				FileChannel fc = null;
				FileInputStream fis = null;
				try {
					fis = new FileInputStream(fileT);
					fc = fis.getChannel();
					bb.clear();
					bb.limit(4 * nValues);
					fc.read(bb, 0);
					buff.clear();
					buff.get(bufferT, 0, nValues);
				} catch (IOException f) {

				} finally {
					if (fc != null) {
						try {
							fc.close();
							fis.close();
						} catch (IOException f) {
							f.printStackTrace();
						}
					}
				}
			} else {
				for (int i = 0; i < nValues; i++)
					bufferT[i] = Integer.MIN_VALUE;
			}
			Ams7fsChannelInfo chanT;
			try {
				chanT = CurrentOpenData.getInstance().getChannelInfoFromID("T_sc");
				for (int i = 0; i < nValues; i++) {
					double val = buffer[i] * chan.getRealSlope();
					double valT = bufferT[i] * chanT.getRealSlope();
					e.setVariable("P_sc", val);
					e.setVariable("T_sc", valT);
					values[i] = e.evaluate();
				}
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		} else if (chan.getSzID().equals("SCL")) {
			for (int i = 0; i < nValues; i++) {
				double val = buffer[i] * chan.getRealSlope();
				e.setVariable("ch4", val);
				values[i] = e.evaluate();
			}
		} else {
			for (int i = 0; i < nValues; i++) {
				double val = buffer[i] * chan.getRealSlope();
				e.setVariable(chan.getSzID(), val);
				values[i] = e.evaluate();
			}
		}
	}

	public double getAverageBetweenTimes(double lTime, double rTime) {
		double leftOffset = getOffsetFromTime(lTime);
		double rightOffset = getOffsetFromTime(rTime);
		long lOffset = (long) Math.floor(leftOffset);
		long rOffset = (long) Math.ceil(rightOffset) + 1;

		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (lOffset < 0)
			lOffset = 0;
		if (rOffset >= totalNumberOfShorts)
			rOffset = totalNumberOfShorts - 1;
		if (lOffset >= rOffset)
			return Double.NaN;

		long nShorts = rOffset - lOffset;
		int skipNeeded = Utils.GetNextPowerOfTwo((int) (nShorts / maxDisplayPoints));
		if (skipNeeded == 0)
			skipNeeded = 1;
		if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip) {
			refillBuffer((rOffset + lOffset) / 2, skipNeeded);
		}

		int lBufferOffset = (int) ((lOffset - lBuffer) / curSkip);
		int nPoints = (int) (nShorts / curSkip);
		int curOffset = lBufferOffset;
		double av = 0;
		long nvals = 0;
		for (int i = 0; i < nPoints; i++) {
			double val = values[curOffset];
			av += val;
			nvals++;
			curOffset++;
		}
		return av / nvals;
	}

	public double getStdDevBetweenTimes(double lTime, double rTime) {
		double leftOffset = getOffsetFromTime(lTime);
		double rightOffset = getOffsetFromTime(rTime);
		long lOffset = (long) Math.floor(leftOffset);
		long rOffset = (long) Math.ceil(rightOffset) + 1;

		if (totalNumberOfShorts == 0)
			totalNumberOfShorts = baseFile.length() / 4;
		if (lOffset < 0)
			lOffset = 0;
		if (rOffset >= totalNumberOfShorts)
			rOffset = totalNumberOfShorts - 1;
		if (lOffset >= rOffset)
			return Double.NaN;

		long nShorts = rOffset - lOffset;
		int skipNeeded = Utils.GetNextPowerOfTwo((int) (nShorts / maxDisplayPoints));
		if (skipNeeded == 0)
			skipNeeded = 1;
		if (lOffset < lBuffer || rOffset > rBuffer || skipNeeded != curSkip) {
			refillBuffer((rOffset + lOffset) / 2, skipNeeded);
		}
		int lBufferOffset = (int) ((lOffset - lBuffer) / curSkip);
		int nPoints = (int) (nShorts / curSkip);
		int curOffset = lBufferOffset;
		double m = 0;
		double s = 0;
		double tmpM = 0;
		int k = 1;
		double realVal;
		for (int i = 0; i < nPoints; i++) {
			double val = values[curOffset];
			realVal = val;
			tmpM = m;
			m += (realVal - tmpM) / k;
			s += (realVal - tmpM) * (realVal - m);
			k++;
			curOffset++;
		}
		if (k < 2)
			return -1;
		return Math.sqrt(s / (k - 2));
	}
}
