package nl.vu.psy.ams.suite.data.structures.sets;

import java.util.ArrayList;
import java.util.SortedSet;
import java.util.TreeSet;

import nl.vu.psy.ams.suite.data.CurrentOpenData;
import nl.vu.psy.ams.suite.data.structures.ECGBeat;
import nl.vu.psy.ams.suite.data.structures.IBIValue;
import nl.vu.psy.ams.suite.main.AppSettings;
import nl.vu.psy.ams.suite.main.AppSettings.Settings;
/*
 * A subset of all ibis, similar to the ones generated by
 * SubsetFileGenerator for signals, to make drawing of large
 * ibi sets (such as the one in the timebar) faster, since not all
 * ibi's have to be drawn if there are more ibi's than pixels in the 
 * screen.
 */
public class SubSetIbiSet {
	// private static SubSetIbiSet	instance;
	// public static SubSetIbiSet getInstance() {
	// 	if (instance == null)
	// 		instance = new SubSetIbiSet();
	// 	return instance;
	// }
	private TreeSet<IBIValue>	ibiValues		= new TreeSet<IBIValue>();
	private TreeSet<Double>		sections		= new TreeSet<Double>();
	private int					ssChangeCount	= 0;
	private double				lTime;
	private double				tW;

	private double				rTime;
	private int					maxDispPoints, channelNo = 0;

	public SubSetIbiSet() {
		reCalculateSubSet(true);
	}

	public SubSetIbiSet(int channel) {
		this.channelNo = channel;
		reCalculateSubSet(true);
	}

	public void changeAroundTime(double time) {
		if (time < lTime || time > rTime)
			return;
		BeatSet beatSet = CurrentOpenData.getInstance().getBeatSet();
		if (beatSet.getBeatBeforeTime(time) != null)
			if (beatSet.getBeatBeforeTime(time).isFirstInSeries())
				return;
		if (beatSet.getBeatAfterTime(time) != null)
			if (beatSet.getBeatAfterTime(time).isFirstInSeries())
				return;
		if (beatSet.getBeatClosestToTime(time) != null)
			if (beatSet.getBeatClosestToTime(time).isFirstInSeries())
				return;

		int tI = (int) ((time - lTime) / tW);
		double curTime = lTime + (tI - 1) * tW;
		double endTime = lTime + (tI + 1) * tW;
		double minIBI, minIBITime = 0, maxIBI, maxIBITime = 0;
		double curIBI;
		boolean minFound, maxFound;

		ArrayList<IBIValue> toBeDeleted = new ArrayList<IBIValue>(ibiValues.subSet(new IBIValue(curTime, 0), true, new IBIValue(endTime, 0), true));
		ibiValues.removeAll(toBeDeleted);

		while (curTime < endTime) {
			minIBI = Double.POSITIVE_INFINITY;
			maxIBI = Double.NEGATIVE_INFINITY;
			minFound = false;
			maxFound = false;
			SortedSet<ECGBeat> bts = beatSet.subSet(curTime, curTime + tW);
			for (ECGBeat b : bts) {
				ECGBeat nb = beatSet.getNextBeat(b);
				if (nb != null) {
					if (nb.isFirstInSeries() == false) {
						curIBI = nb.getRPeakTime() - b.getRPeakTime();
						if (curIBI > maxIBI) {
							maxIBI = curIBI;
							maxIBITime = b.getRPeakTime();
							maxFound = true;
						}
						if (curIBI < minIBI) {
							minIBI = curIBI;
							minIBITime = b.getRPeakTime();
							minFound = true;
						}
					}
				}
			}
			if (minFound)
				ibiValues.add(new IBIValue(minIBITime, minIBI));
			if (maxFound)
				ibiValues.add(new IBIValue(maxIBITime, maxIBI));
			curTime += tW;
		}
		ssChangeCount++;
	}

	public TreeSet<IBIValue> getIBIValues() {
		return ibiValues;
	}

	public TreeSet<Double> getSections() {
		return sections;
	}

	public void reCalculateSubSet(boolean force) {
		BeatSet beatSet = CurrentOpenData.getInstance().getBeatSet(channelNo);
		if (ssChangeCount == beatSet.getChangeCount() && force == false)
			return;
		ssChangeCount = beatSet.getChangeCount();
		if (beatSet.getBeats().isEmpty())
			return;
		maxDispPoints = AppSettings.getInstance().getIntProperty(Settings.MAXDISPLAYPOINTS);
		lTime = beatSet.getBeats().first().getRPeakTime();
		rTime = beatSet.getBeats().last().getRPeakTime();
		double tWidth = rTime - lTime;
		tW = 2 * tWidth / maxDispPoints;
		double minIBI, minIBITime = 0, maxIBI, maxIBITime = 0;
		double curIBI;
		double curTime = beatSet.getBeats().first().getRPeakTime();
		boolean minFound, maxFound;
		ibiValues.clear();
		sections.clear();
		while (curTime < rTime) {
			minIBI = Double.POSITIVE_INFINITY;
			maxIBI = Double.NEGATIVE_INFINITY;
			minFound = false;
			maxFound = false;
			SortedSet<ECGBeat> bts = beatSet.subSet(curTime, curTime + tW);
			for (ECGBeat b : bts) {
				if (b.isFirstInSeries())
					sections.add(b.getRPeakTime());
				ECGBeat nb = beatSet.getNextBeat(b);
				if (nb != null) {
					if (nb.isFirstInSeries() == false) {
						curIBI = nb.getRPeakTime() - b.getRPeakTime();
						if (curIBI > maxIBI) {
							maxIBI = curIBI;
							maxIBITime = b.getRPeakTime();
							maxFound = true;
						}
						if (curIBI < minIBI) {
							minIBI = curIBI;
							minIBITime = b.getRPeakTime();
							minFound = true;
						}
					}
				}
			}
			if (minFound)
				ibiValues.add(new IBIValue(minIBITime, minIBI));
			if (maxFound)
				ibiValues.add(new IBIValue(maxIBITime, maxIBI));
			curTime += tW;
		}
	}

}
